version: '2'
services:
    gpweb-app:
        image: gpweb
        external_links:
            - gpweb-postgresql:postgresql
            - gpweb-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/gpweb
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    gpweb-postgresql:
        extends:
            file: postgresql.yml
            service: gpweb-postgresql
    gpweb-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gpweb-elasticsearch
